package main

// ----------------------------------------------------------------------------
// Code generated by `Steve Smith <wearypossum4770@yahoo.com>`. DO NOT EDIT.
//
// See scripts/generate-api.sh
// ----------------------------------------------------------------------------
import (
	"example.com/arraymanipulations"
	"example.com/greetings"
	"example.com/stringmanipulations"
	"example.com/veryeasy"
	"fmt"
	"log"
)

func main() {
	// Set properties of the predefined Logger, including
	// the log entry prefix and a flag to disable printing
	// the time, source file, and line number.
	veryeasy.Addition(20, 30)
	ip := stringmanipulations.DefangIPAddr("1.1.1.1")
	words := stringmanipulations.ReverseWords("this is a sentence")
	summation := arraymanipulations.ReduceArray(1, 2, 3, 4)
	fmt.Println("the sum of integers in the array: ", summation)
	fmt.Println(ip)
	fmt.Println(words)
	fmt.Println("Hello GO!")
	log.SetPrefix("greetings: ")
	log.SetFlags(0)
	// Request a greeting message.
	message, err := greetings.Hello("")
	// If an error was returned, print it to the console and
	// exit the program.
	if err != nil {
		log.Fatal(err)
	}
	// If no error was returned, print the returned message
	// to the console.
	fmt.Println(message)
}
